### ISSUE TITLE
Upgrade to Golang 1.9

### ISSUE THREAD

**Issue by sschuberth** [carstn/chocolatey-packages#19]
Could we please get an upgrade to Golang 1.9?

**Comment by carstn** [comment]
This is resolved in PR #20. The Go 1.9 package has been pushed to chocolatey.org/packages/golang.

**Comment by brianselby** [comment]
[git-lfs-2.3.4.zip](https://github.com/carstn/chocolatey-packages/files/1737836/git-lfs-2.3.4.zip)
